### ISSUE TITLE
Expose ZIP 317

### ISSUE THREAD

**Issue by LukasKorba** [Electric-Coin-Company/zcash-swift-wallet-sdk#1204]

**Comment by str4d** [comment]
In a pairing today, @nuttycom and I decided that we will change `Synchronizer.proposeShielding` in three ways:
- It will take an optional transparent receiver, corresponding to a specific diversified UA (or the default transparent address) that should have its transparent funds shielded.
  - If the transparent receiver is not part of the specified account, an error will be returned.
  - If no receiver is provided, the current behaviour of "shield transparent funds in whichever transparent receiver under the account has them" will be used.
- It will return an error if there are transparent funds in more than one transparent receiver in the given account.
  - This fixes an address linkability problem that currently exists with `Synchronizer.shieldFunds`, wherein a transaction spending funds from multiple transparent receivers in the same account can be created which indelibly links them on-chain.
  - We are not fixing the problem in `Synchronizer.shieldFunds` because working around it would require changing the `shieldFunds` API, but we are deprecating and soon removing the method instead.
- It will return `nil` if there are no funds to shield (i.e. its proposal will be "do nothing"), a la https://github.com/zcash/librustzcash/issues/1200.

The transparent receiver argument serves two functions:
- It is a (more complicated but safer) escape hatch to use when the new "multiple transparent receivers" error is encountered.
- It enables SDK users to implement their own mecahnism for avoiding address linkability when shielding funds, in the interim while we do not have our own solution (https://github.com/zcash/librustzcash/issues/1201).
